apiVersion: 1

datasources:
  - name: VentilTester PostgreSQL
    type: grafana-postgresql-datasource
    access: proxy
    url: host.docker.internal:5432
    database: ventiltester
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true
